# Generated by Django 4.2.29 on 2026-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0002_doctor_bio_doctor_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
