# Generated by Django 4.2.29 on 2026-03-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0003_doctor_clinic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(blank=True, help_text='e.g., MD from Harvard Medical School', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.CharField(blank=True, help_text='e.g., English, Bengali', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Dhaka, Bangladesh', max_length=255),
        ),
    ]
